# Namespace where the chart is deployed (separate from target namespaces)
namespace: codeartifact-secret-updater

# Name of the secret to create/update
secretName: "codeartifact-secret"

# AWS configuration
aws:
  # Required: AWS region
  region:
  # Required: AWS account ID
  accountId:
  # Optional: AWS access key ID and secret access key
  # accessKeyId: ""
  # secretAccessKey: ""

# CodeArtifact configuration
codeartifact:
  # Required: CodeArtifact domain
  domain:

# Target namespaces to manage secrets in
targetNamespaces: []

# CronJob configuration
cronJob:
  # Run every 12 hours
  schedule: "0 */12 * * *"
  # TTL for the CronJob
  ttlSecondsAfterFinished: 600
  image:
    # GitHub Container Registry
    repository: "ghcr.io/christian-deleon/awscli-kubectl"
    # Default tag
    tag: "0.1.0"
