apiVersion: v1
kind: ConfigMap
metadata:
  name: update-codeartifact-secret
data:
  update-codeartifact-secret.sh: |
    #!/bin/sh -e

    TOKEN=$(
      aws codeartifact get-authorization-token \
        --domain {{ .Values.codeartifact.domain }} \
        --domain-owner {{ .Values.aws.accountId }} \
        --query authorizationToken \
        --output text
    )

    for ns in $NAMESPACES; do
      echo "Updating secret in namespace: $ns"

      # Create or update the secret
      kubectl create secret generic {{ .Values.secretName }} \
        --from-literal=CODEARTIFACT_TOKEN=$TOKEN \
        --dry-run=client -o yaml | kubectl apply -f - -n $ns
    done
