apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-script
data:
  update-codeartifact-secret.sh: |
    #!/bin/sh -e

    echo "Getting authorization token for CodeArtifact"

    NAMESPACES={{ join " " .Values.targetNamespaces }}

    if [ -z "$NAMESPACES" ]; then
      echo "No namespaces provided"
      exit 1
    fi

    TOKEN=$(
      aws codeartifact get-authorization-token \
        --domain {{ required "codeartifact.domain is required" .Values.codeartifact.domain }} \
        --domain-owner {{ required "aws.accountId is required" .Values.aws.accountId }} \
        --region {{ required "aws.region is required" .Values.aws.region }} \
        --query authorizationToken \
        --output text
    )

    for ns in $NAMESPACES; do
      echo "Updating secret in namespace: $ns"

      # Create or update the secret
      kubectl create secret generic {{ .Values.secretName }} \
        --from-literal=token=$TOKEN \
        --dry-run=client -o yaml | kubectl apply -f - -n $ns

      if [ $? -eq 0 ]; then
        echo "Secret updated in namespace: $ns"
      else
        echo "Failed to update secret in namespace: $ns"
      fi
    done
