apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  ttlSecondsAfterFinished: {{ .Values.cronJob.ttlSecondsAfterFinished }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          restartPolicy: OnFailure
          containers:
            - name: codeartifact-secret-updater
              image: {{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}
              command: ["/bin/sh", "/app/update-codeartifact-secret.sh"]
              {{- if and .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
              {{- end }}
              volumeMounts:
                - name: script
                  mountPath: /app/update-codeartifact-secret.sh
                  subPath: update-codeartifact-secret.sh
          volumes:
            - name: script
              configMap:
                name: {{ .Release.Name }}-script
                defaultMode: 0755
